name: 🚑 Undo Last Mistake

on:
  workflow_dispatch:

jobs:
  revert-mistake:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        branch: [PLTS, st74, st78, ksun-33024, ksun-33068, resukisu, susfs]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ExXyrou/android_san_kernel_xiaomi_sdm660
          ref: ${{ matrix.branch }}
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Undo Last Commit & Force Push
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          
          echo "Membatalkan 1 commit terakhir pada branch ${{ matrix.branch }}..."
          git reset --hard HEAD~1
          
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/ExXyrou/android_san_kernel_xiaomi_sdm660.git
          
          # Force push untuk memaksa GitHub kembali ke masa lalu
          git push origin HEAD:${{ matrix.branch }} --force
          echo "✅ Branch ${{ matrix.branch }} berhasil dikembalikan."
